### ISSUE TITLE
SocketException because of not closed ftp connections

### ISSUE THREAD

**Issue by nesokreso** [wso2-attic/esb-connectors#560]
Hi, 

I am using fileconnector version 1.0.0 in a customer project. Since the 17.09.2016 the application is productive. My problem is that the wso2 esb fileconnector opens ftp connections to another system without closing them. With netstat it shows me many thousands connections in CLOSE_WAIT state. When the configured socket maximum of 15000 is exceeded, the server throws a socketexception:

TID: [-1234] [] [2016-10-05 20:00:34,018] ERROR {org.apache.commons.vfs2.provider.ftps.FtpsClientFactory} -  java.net.SocketException: No buffer space available (maximum connections reached?): connect {org.apache.commons.vfs2.provider.ftps.FtpsClientFactory}
TID: [-1234] [] [2016-10-05 20:00:34,020] ERROR {org.wso2.carbon.connector.FileCopyInStream} -  Could not connect to FTP server on "ftp-secure.sbb.ch". {org.wso2.carbon.connector.FileCopyInStream}

How can i fix it? Is it fixed in fileconnector version 2.0.0? Why isn't there longer a rename function in fileconnector 2.0.0?

Best regards
Nenad

**Comment by vives** [comment]
Hi ,

You can use move[1] operation to rename the file using file connector version 2. You can find the latest version in [2].
[1] https://docs.wso2.com/display/ESBCONNECTORS/Working+with+the+File+Connector+Version+2#WorkingwiththeFileConnectorVersion2-move
[2] https://store.wso2.com/store/assets/esbconnector/details/48bab332-c6a6-4f5a-9b79-17e29c7ad4c6
